### ISSUE TITLE
Removal-of-support-for-TLS-protocol-versions-1-0-and-1-1

### ISSUE THREAD

**Issue by RustinAlexandru** [mozts2005/ZendeskApi_v2#352]
https://support.zendesk.com/hc/en-us/articles/360000710347-Removal-of-support-for-TLS-protocol-versions-1-0-and-1-1

Hello. We are having the following problem when using your wrapper.  

"The request was aborted: Could not create SSL/TLS secure channel.Error content:  
 Resource String: tickets/25890.json  + "

Stacktrace : 
``
   at ZendeskApi_v2.Core.RunRequest(String resource, String requestMethod, Object body, Nullable`1 timeout, Dictionary`2 formParameters)
   at ZendeskApi_v2.Core.RunRequest[T](String resource, String requestMethod, Object body, Nullable`1 timeout, Dictionary`2 formParameters)
   at ZendeskApi_v2.Core.GenericGet[T](String resource)
   at ZendeskApi_v2.Requests.Tickets.GetTicket(Int64 id, TicketSideLoadOptionsEnum sideLoadOptions)
   at RS.Platform.BL.ZendeskManager.GetTicket(Int64 id) in D:\Projects\Git\RS\Deployment\RS.Platform\RS.Platform.BL\ZendeskManager.cs:line 28
``

Is this solved or are we waiting for a fix? Thanks. Please ask for any other needed information.

**Comment by rwjdk** [comment]
Issue is described here: https://github.com/mozts2005/ZendeskApi_v2/issues/339

**Short version:**
You need to handle this in you own part of the code as if it was added to the framework itself it could potentially break other parts of your code
