### ISSUE TITLE
Time outs while uploading data

### ISSUE THREAD

**Issue by Cassidie** [mozts2005/ZendeskApi_v2#365]
I'm using the api to upload data to Zendesk. After about 10-15 minutes of my task running, The application throws an exception due to timing out. It's not due to one specific request. Sometimes it's when I'm searching for existing objects and sometimes it's when I'm trying to create a new organization/user/membership.  At first I was using one ZendeskApi object for the whole application lifetime, but I thought that might be the reason for the timing out. So I new up a ZendeskApi before every api call. Still no change in my app timing out. I didn't see anywhere in your docs about disposing of the ZendeskApi, nor did I see anything referencing IDisposable. Any advice on how to fix this? Thanks!

**Comment by Cassidie** [comment]
I found this line a in GetFromData and GetFromDataAsync of Core.cs:
`var postDataStream = new MemoryStream();`

I don't see anywhere we're disposing of this MemoryStream. We're just returning it and using it to write to the requestStream. Could this be the problem?

**Comment by mozts2005** [comment]
That would not be a timeout exception so I would need to see the stack trace to know for sure but not disposing of the stream is not a good thing. 

however, disposing of the client on every call would cause other issues with the max number of TCP connects that can be open. 

please post a stack trace and or a unit test that can reproduce the issue and I will make this a high priority. 

Another thing to think about is that zendesk has [rate limits](https://developer.zendesk.com/rest_api/docs/core/introduction#rate-limits) so you may need to bactch your taks and place a wait/sleep to allow for that.

**Comment by mozts2005** [comment]
some other reading on why we don't use Idisposable in most places 

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
https://blogs.msdn.microsoft.com/alazarev/2017/12/29/disposable-finalizers-and-httpclient/

**Comment by Cassidie** [comment]
Thank you so much for your response! It's been a few days that I've been struggling with our task timing out. I will put our code back that creates the ZendeskApi object only once. And thanks for the reference links!

- Stacktrace:
```
System.Net.WebException: The operation has timed out
at ZendeskApi_v2.Core.RunRequest(String resource, String requestMethod, Object body, Nullable`1 timeout, Dictionary`2 formParameters)
at ZendeskApi_v2.Core.RunRequest[T](String resource, String requestMethod, Object body, Nullable`1 timeout, Dictionary`2 formParameters)
at ZendeskApi_v2.Core.GenericPost[T](String resource, Object body)\r\n   at Infrastructure.EntitySynchronizers.Zendesk.ZendeskApiInteractor.CreateOrganization(Organization organization)
```
- We're using ZendeskApi_v2, Version=3.8.0.0

- Here's the implementation of the last line of the stacktrace as well (i.e. ZendeskApiInteractor.CreateOrganization(Organization organization) 
```
            IndividualOrganizationResponse response = this.zendeskApi.Organizations.CreateOrganization(organization);
            return response.Organization.Id.Value;
```
*NOTE: We do not get the time out exception with the same request every time. However, it has been a line where we are making requests to the API.

- As far as the rate limits, I would figure we'd get a "Exceeds rate limit" exception rather than a time out, but sometimes I do get the program to run a little longer while stepping through during debugging. I did try a few sleeps in the program, but they were seconds, not minutes. I will try adding longer sleeps since it looks like even the basic plan rate limit is 10 per minute.

Again thank you very much for your advice!

**Comment by mozts2005** [comment]
I think we can do a refactor to allow you to set the timeout but it will have to be part of 3.10
